### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Krupaly2k** [kunalvarma05/dropbox-php-sdk#75] opened 2017-10-03 07:48 UTC
Hi,

I need a quick help on this. Please let me know how can I use it for displaying dropbox files as I was using V1 before.

**Comment by Krupaly2k** [comment] 2017-10-03 07:55
I am facing below issue Fatal error: Class 'PHPUnit\Framework\TestCase' not found in C:\xampp\htdocs\dropbox-php-sdk-master\tests\DropboxTest.php on line 5

**Comment by kunalvarma05** [comment] 2017-10-10 15:03
Can you be more specific as to when do you face this error, under what scenario? 

Also, have you run `composer install`?

**Comment by kunalvarma05** [comment] 2017-10-10 15:05
Duplicate of #72

**Closed** 2017-10-11 06:49 UTC
Labels: duplicate
