### ISSUE TITLE
Get shared folder url in public directory

### ISSUE THREAD

**Issue by gety9** [kunalvarma05/dropbox-php-sdk#66] opened 2017-09-26 16:40 UTC
Hi,

I have public dropbox directory that have folder photos, photos folder have folders with numeric names 193112910, 193112911, 193112912, etc.

(public>photos>193112XXX)

I need to get dropbox link for numeric folders. For example i pass 193112910 parameter, and want to get dropbox link for this folder. For example https://www.dropbox.com/sh/XXXXy0v3xbry7yd/AABeBvWMaqXXXXcQAEVhSQza?dl=0

Can i do that using your SDK?

You stated on Jul 12, 2016 that "Currently the SDK covers the auth, files & users endpoints. Will start implementing the sharing endpoints soon. ", so i am not sure if it will work.

Public directory is already shared by default, so i just need to get dropbox link for specific directory.

**Comment by kunalvarma05** [comment] 2017-09-27 19:07
The issue is a possible Duplicate of #1. 

If you're looking for the sharing endpoints, you can work with them through the SDK. It doesn't have dedicated methods for interacting with the sharing endpoints, however, the SDK can still make requests to the sharing endpoints and fetch/decode data. 

See the [Create Shared Link with Settings](https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings) documentation on Dropbox's developer site.

**Closed by kunalvarma05** 2017-09-27 19:07 UTC
